# Generated by Django 5.1.2 on 2024-10-24 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_Registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Habitaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_Habitacion', models.CharField(max_length=50)),
                ('tipo_Habitacion', models.CharField(max_length=100)),
                ('precioPorNoche', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_Entrada', models.DateField()),
                ('cantidad_Noches', models.IntegerField()),
                ('fecha_Reserva', models.DateField(auto_now_add=True)),
                ('Clientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clientes')),
                ('Habitaciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.habitaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('metodoPago', models.CharField(max_length=100)),
                ('fechaPago', models.DateField()),
                ('Reservas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reservas')),
            ],
        ),
    ]
